config/routes.rb
Rails.application.routes.draw do
  # write custom routes here
  root "sessions#home"

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  #login route
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  #logout route
  delete '/logout' => 'sessions#destroy'

  #omniauth callback route
  get '/auth/:provider/callback' => 'sessions#omniauth'

  resources :cities
   resources :blogs do
     resources :comments
   end
  resources :comments
  resources :users do
    resources :blogs, only: [:new, :create, :index, :show, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :newest, -> { order(created_at: :desc) }
  scope :oldest, -> { order(created_at: :asc) }
  scope :freshest, -> { order(updated_at: :desc) }
  scope :stalest, -> { order(updated_at: :asc) }
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  belongs_to :city
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  validates :title, :content, presence: true
  validates :city, presence: true
  validate :too_many_blogs

  def self.search(params)
    where("LOWER(title) LIKE ?", "%#{params}%")
  end

  scope :most_comments, -> {left_joins(:comments).group('blogs.id').order('count(comments.blog_id) desc')}

  def city_attributes=(attr)
    self.city = City.find_or_create_by(attr) if !attr[:name].blank?

  end

  def too_many_blogs
    blogs_of_today = user.blogs.select do |b|
      b.created_at.try(:to_date) == Date.today
    end
    if blogs_of_today.size > 5
      errors.add(:blog_id, "too many blogs today")
    end
  end
end

app/models/city.rb
class City < ApplicationRecord
  has_many :blogs
  has_many :users, through: :blogs

  validates :name, presence: true

  scope :by_name, -> { order(name: :asc) }

  def to_s
    name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commented_trips, through: :comments,
    source: :blog
  has_secure_password
  has_many :cities, through: :blogs

  validates :email, :username, presence: true, uniqueness: true
  validates :username, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #gives access to methods in the views
  helper_method :current_user, :logged_in?

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!session[:user_id]
  end

  def redirect_if_not_logged_in
    redirect_to '/' if !logged_in?
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:update, :destroy]

  def new
    if params[:user_id] && @user = User.find_by_id(params[:user_id])
      @blog = @user.blogs.build
    else
      @blog = Blog.new
    end
    @blog.build_city
  end

  def index
    if params[:user_id] && @user = User.find_by_id(params[:user_id])
      @blogs = @user.blogs.newest
    else
      @error = "User doesn't exist" if params[:user_id]
      @blogs = Blog.newest
    end
    if params[:q] && !params[:q].empty?
      @blogs = @blogs.search(params[:q].downcase)
    end
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end

  def show; end

  def destroy
    @blog.destroy

    redirect_to current_user
  end

  def edit; end

  def update
    if @blog.update(blog_params)
      redirect_to blog_path(@blog)
    else
      render :edit
    end
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def authenticate_user!
    redirect_to blogs_path if @blog.user != current_user
  end

  def blog_params
    params.require(:blog).permit(:title, :content, :user_id, :city_id)
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :redirect_if_not_logged_in

  def new
    @city = City.new
  end

  def index
    if params[:user_id] && @user = User.find_by_id(params[:user_id])
      @cities = @user.city.by_name
    else
      @error = "That city doesn't exist" if params[:blog_id]
      @cities = City.by_name
    end
  end

  def create
    @city = City.new(city_params)
    if @city.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @city = City.find(params[:id])
  end

  private

  def city_params
    params.require(:city).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :set_comment, only: [:show, :edit, :update]
  before_action :redirect_if_not_comment_author, only: [:edit, :update]

  def index
    if params[:blog_id] && @blog = Blog.find_by_id(params[:blog_id])
      @comments = @blog.comments
    else
      @error = "That blog doesn't exist" if params[:blog_id]
      @comments = Comment.all
    end
  end

  def new
    if params[:blog_id] && @blog = Blog.find_by_id(params[:blog_id])
      @comment = @blog.comments.build
    else
      @error = "That blog doesn't exist" if params[:blog_id]
      @comment = Comment.new
    end
  end

  def create
    @comment = current_user.comments.build(comment_params)

    if @comment.save
      redirect_to @comment.blog
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    redirect_to comments_path if @comment.user != current_user
    if @comment.update(comment_params)
      redirect_to comment_path(@comment)
    else
      render :edit
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :blog_id)
  end

  def set_comment
    @comment = Comment.find_by(id: params[:id])
    if !@comment
      flash[:message] = "Comment was not found"
      redirect_to comments_path
    end
  end

  def redirect_if_not_comment_author
    redirect_to comments_path if @comment.user != current_user

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def destroy
    session.clear
    redirect_to root_path
  end

  def create
    user = User.find_by(username: params[:user][:username])
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:message] = "Oops, please try again"
      redirect_to "/login"
    end
  end

  def omniauth
    @user = User.find_or_create_by(email: auth["info"]["email"]) do |user|
      user.username = auth["info"]["first_name"]
      user.password = SecureRandom.hex
    end
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to '/'
    end

  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    redirect_if_not_logged_in
    @user = User.find_by_id(params[:id])
    redirect_to '/' if !@user
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def index_header
    if @user
      content_tag(:h1, "#{@user.username}'s Blogs:")
    else
      content_tag(:h2, "All Blogs")
    end
  end

  def display_blogs

    if @user.blogs.empty?
      content_tag(:h2) do
        "No blogs yet, create a blog now!".html_safe +
          link_to('Share', new_blog_path)
      end
    else
      content_tag(:h2, "Your Blogs:") +
        render(@user.blogs)
    end
  end
end

app/views/blogs/_blog.html.erb
<div class="mb-3 p-3 border bg-white">
  <%= link_to blog.title, blog_path(blog)%>
  • Created at <%= blog.updated_at.strftime("%I:%M %p on %m/%d/%Y") %>
  • <%= link_to blog.comments.count, blog_path(blog) %> Comments
</div>

app/views/blogs/edit.html.erb
<h1>Edit Blog <%=@blog.title%>!</h1>

<%= render partial: "layouts/errors", locals: {object: @blog} %>

<%= form_for(@blog) do |f| %>

  <%= f.label "Choose your City:" %>
  <%= f.collection_select :city_id, City.all, :id, :name, include_blank: true %><br>

  <br>
  <br>

  <%= f.label :title %><br>
  <br>
  <%= f.text_field :title %><br>
  <br>

  <%= f.label :content %><br>
  <br>
  <%= f.text_area :content %><br>
  <br>

  <%= f.submit "Edit Blog", class: "btn btn-primary btn-lg" %><br>
  <br>

<% end %>

app/views/blogs/index.html.erb
<h1><%= index_header %></h1><br>

<%= form_tag("/blogs", method: "get") do %>
  <%= label_tag(:q, "Search for Blogs Here:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %><br>

<% if @blogs.empty? %>
  <h2>No blogs yet, create a blog now! <%= link_to "Share", new_blog_path %></h2>
<% else %>

  <%= render @blogs %>

<% end %>

app/views/blogs/new.html.erb
<h1>New Blog!</h1>

<%= render partial: "layouts/errors", locals: {object: @blog} %>

<%= form_for(@blog) do |f| %>

  <%= f.label "Choose your City:" %>
  <%= f.collection_select :city_id, City.all, :id, :name, include_blank: true %><br>
  <br>

  </p>

  <br>
  <br>

  <%= f.label :title %><br>
  <br>
  <%= f.text_field :title %><br>
  <br>

  <%= f.label :content %><br>
  <br>
  <%= f.text_area :content %><br>
  <br>

  <%= f.submit "Submit", class: "btn btn-primary btn-lg" %><br>
  <br>

<% end %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1><br>
<h2>Written by: <%=@blog.user.username %></h2><br>

<h3>City: <%= @blog.city.try(:name)%></h3><br>
<% if @blog.user == current_user %>
  <h4><%= link_to "Edit", edit_blog_path(@blog), class: 'btn btn-secondary' %></h4><br>
  <h4><%= button_to 'Delete', @blog,  method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></h4><br>
<% end %>

<div class="mb-3 p-3 border bg-white"><%= @blog.content %></div><br><br>

<p><%= link_to 'Add a New Comment', new_blog_comment_path(@blog), class: 'btn btn-secondary' %></p><br>

<% if !@blog.comments.empty? %>
  <h4> All Comments:</h4><br><br>

  <% @blog.comments.order(updated_at: :desc).limit(3).each do |c| %>
    <div>
      <strong><%=c.user.username%></strong><br><br>

      <p><%= link_to c.content, blog_comment_path(@blog,c)%> at <%= c.updated_at.strftime("%I:%M %p on %m/%d/%Y")%></p><br>
    </div><br>
  <% end %>
<% end %>

app/views/cities/_city.html.erb
<div>
  <p><%= link_to city.name, city_path(city)%></p><br>
</div>

app/views/cities/_no_blogs.html.erb
<p>Sorry no blogs at this time.</p>

app/views/cities/index.html.erb
<h4>All Cities:</h4>

<br><br>

<%= render @cities %>

app/views/cities/show.html.erb
<h1><%= @city %></h1>

<%= render(@city.blogs) || render('no_blogs') %>

app/views/comments/edit.html.erb
<h1>Edit Comment!</h1>

<%= render partial: "layouts/errors", locals: {object: @comment} %><br>


<%= form_for(@comment) do |f|%>

    <%= f.label :blog %>
    <%= f.collection_select :blog_id, Blog.all, :id, :title %>

     <br><br>

    <%= f.label :content %>
    <%= f.text_area :content %><br>
    <br>

  <%= f.submit "Edit Comment", class: "btn btn-primary btn-lg" %><br>

<% end %>

app/views/comments/new.html.erb
<% if @comment.blog %>
  <h1>New Comment for <%=@comment.blog.title %>!</h1><br>
<% else %>
  <h1>New Comment!</h1><br>
<% end %>

<%= render partial: "layouts/errors", locals: {object: @comment} %><br>


<%= form_for([@comment.blog,@comment]) do |f|%>

  <%if !@comment.blog %>
    <br>
    <%= f.label :blog %>
    <%= f.collection_select :blog_id, Blog.all, :id, :title %><br>
  <% else %>
    <%= f.hidden_field :blog_id %>
  <% end %>
  <br>
  <br>

  <%= f.label :content %>
  <%= f.text_area :content %><br>
  <br>
  <%= f.submit "Comment", class: "btn btn-primary btn-lg" %><br>

<% end %>

app/views/comments/show.html.erb
<h2><%= @comment.content %> • <%= @comment.user.username %></h2><br>

<h4>Click here to view blog details: <%= link_to @comment.blog.title, blog_path(@comment.blog_id) %></h4><br><br>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travelgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
    <% if logged_in? %>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <%= link_to "Add a Blog", new_blog_path, class: "nav", class: 'btn btn-light btn-sm'%>  •
        </li>
        <li class="nav-item">
          <%= link_to "View All Blogs", blogs_path, class: 'btn btn-light btn-sm'%>  •
        </li>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: 'btn btn-light btn-sm'%>  •
        </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete, class: 'btn btn-light btn-sm'%>
        </li>
        <li class="nav-item">
           • <%= link_to "View My Blogs", user_blogs_path(current_user), class: 'btn btn-light btn-sm'%>
        </li>
      </ul>
  <% else %>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <%= link_to "Log In", login_path, class: 'btn btn-primary' %> •
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", signup_path, class: 'btn btn-primary' %>
        </li>
      </ul>
    <% end %>
  </div>

  <div>
    <% if flash[:message] %>
      <%= flash[:message] %>
    <% end %>

    <%= @error %>
  </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for(@user) do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %><br>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <br>
  <%= f.submit "Sign Up", class: "btn btn-primary btn-lg" %><br>
  <br>
<% end %>

app/views/users/show.html.erb
<h1> Welcome Traveler <%= @user.username %>!</h1>

<%= display_blogs %>